//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingCardCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkout
    {
        public int Id { get; set; }
        public int OrderDetailId { get; set; }
        public int UserID { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailID { get; set; }
    
        public virtual Register Register { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
